facebook:
    client:
      clientId: 2283N8
      clientSecret: 8f85d6c937a316cf73db546589c44c25
      accessTokenUri: https://api.fitbit.com/oauth2/token
      userAuthorizationUri: https://www.fitbit.com/oauth2/authorize
      tokenName: oauth_token
      authenticationScheme: query
      response_type: token
      scope: activity
      redirect_uri: http://veninsoft-trackfit.44fs.preview.openshiftapps.com/fitbitcallback
    resource:
      userInfoUri: https://api.fitbit.com/1/user/2YP77C/profile.json


logging:
  level:
    org.springframework.security: DEBUG